apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    protected-mode no
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    
    # Replication
    replicaof redis-0.redis-headless 6379
    replica-serve-stale-data yes
    replica-read-only yes
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Performance tuning
    tcp-keepalive 60
    timeout 0
    tcp-backlog 511
    databases 16
    maxclients 10000