apiVersion: batch/v1
kind: Job
metadata:
  name: database-restore
spec:
  template:
    spec:
      containers:
        - name: restore
          image: postgres:14
          command:
            - /bin/sh
            - -c
            - |
              # Download from object storage
              aws s3 cp s3://$BACKUP_BUCKET/$BACKUP_FILE /backup/
              # Restore database
              pg_restore -h postgresql -U $POSTGRES_USER -d urlshortener -c /backup/$BACKUP_FILE
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: BACKUP_BUCKET
              value: "url-shortener-backups"
            - name: BACKUP_FILE
              value: "postgres_YYYYMMDD_HHMMSS.dump"  # Replace with actual backup file
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret-key
          volumeMounts:
            - name: restore
              mountPath: /backup
      volumes:
        - name: restore
          emptyDir: {}
      restartPolicy: Never